// FONTS FOR HERO [ http://www.awwwards.com/awwwards/collections/free-fonts/ ]
                // [http://befonts.com/]
// FONTS [https://www.fontsquirrel.com]
// HERO VIDEO & code to it [ http://www.coverr.co/ ]
// FREE MOCKUPS PSD ICONS ETC [ https://sellfy.com/designcoon ]
